# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b9392263aa46c63e83991e654997451b369e39acc5185b8984fd546a251bb18c15f5062fb116a1208037ec141ee153af7baea8fb40c0f7dee5cdc4a42f0bdc

test:
  secret_key_base: 8b95d5a7668a7b470490c47e1c487bf984e0807fb20070ce1a7b047c514abfdccf74f8bad4e77eb16d45ad7955f8c46d2de356f24c0224a6a42ed75f3d88931d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
